# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1267f00a8a12d54189126896d180d19b46d429e1566f4ab9bc10aeb4fef6b309d8d090bf735856d61e987392d1e4aa8912bee48e8084e50bba091da38c7198c6

test:
  secret_key_base: 5745bf644612316c60a9492d9c3082372c19aea1318ec20e86eaf35b285510e5454daa593722611795d7cf025f03fd612e4c6e5c32253c6069b3815cb14f9f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
